"""empty message

Revision ID: cd185fa49d08
Revises: 
Create Date: 2020-05-25 07:11:49.142369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd185fa49d08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholar_student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('day_birth', sa.Integer(), nullable=True),
    sa.Column('month_birth', sa.Integer(), nullable=True),
    sa.Column('year_birth', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('race', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.Integer(), nullable=True),
    sa.Column('uf_birth', sa.Integer(), nullable=True),
    sa.Column('city_birth', sa.Integer(), nullable=True),
    sa.Column('disability', sa.Integer(), nullable=True),
    sa.Column('public_transp', sa.Integer(), nullable=True),
    sa.Column('school_uf', sa.Integer(), nullable=True),
    sa.Column('school_dependency', sa.Integer(), nullable=True),
    sa.Column('school_location', sa.Integer(), nullable=True),
    sa.Column('class_type', sa.Integer(), nullable=True),
    sa.Column('class_duration', sa.Integer(), nullable=True),
    sa.Column('class_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scholar_student')
    # ### end Alembic commands ###
